import imageMeeting from "@/images/meeting.jpg";
import imageWhiteboard from "@/images/whiteboard.jpg";
import imageLaptop from "@/images/laptop.jpg";

export const projects = [
  {
    id: "PRJ-001",
    title: "Global Banking Platform Transformation",
    client: "SecureBank International",
    category: "Enterprise Software",
    status: "completed",
    duration: "18 months",
    year: "2024",
    team: ["Strategy Lead", "UX Director", "Solution Architect", "DevOps Lead", "QA Manager", "Security Consultant"],
    description: "A complete digital transformation of a legacy banking infrastructure serving 12 million customers across 35 countries.",
    tags: ["FinTech", "Enterprise", "Cloud Migration", "Microservices"],
    image: imageLaptop,
    slug: "securebank-digital-transformation",
    featured: true,
  },
  {
    id: "PRJ-002",
    title: "E-commerce Marketplace Platform",
    client: "Artisan Market",
    category: "E-commerce",
    status: "completed",
    duration: "14 months",
    year: "2023",
    team: ["Product Manager", "UX Designer", "Frontend Lead", "Backend Engineer", "Data Scientist", "DevOps Engineer"],
    description: "Built a global multi-vendor marketplace connecting 15,000+ artisans from 45 countries with customers worldwide.",
    tags: ["E-commerce", "Marketplace", "Fintech", "Global"],
    image: imageMeeting,
    slug: "artisan-marketplace",
    featured: true,
  },
  {
    id: "PRJ-003",
    title: "Healthcare Patient Experience Platform",
    client: "MediCare Plus Network",
    category: "Healthcare",
    status: "completed",
    duration: "20 months",
    year: "2024",
    team: ["Healthcare Strategist", "UX Researcher", "Product Designer", "HIPAA Compliance Officer", "Engineering Lead", "QA Specialist"],
    description: "An integrated healthcare platform serving 2.5M patients across 200+ facilities with telemedicine and AI-powered features.",
    tags: ["Healthcare", "Telemedicine", "HIPAA", "Enterprise"],
    image: imageWhiteboard,
    slug: "medicare-patient-platform",
    featured: true,
  },
  {
    id: "PRJ-004",
    title: "AI-Powered Enterprise Analytics Suite",
    client: "GlobalTrade Solutions",
    category: "Enterprise Software",
    status: "completed",
    duration: "16 months",
    year: "2024",
    team: ["AI/ML Lead", "Data Engineer", "Product Manager", "UX Designer", "Backend Architect", "Data Scientist"],
    description: "A comprehensive supply chain analytics platform processing 2.5TB of data daily with AI-powered demand forecasting.",
    tags: ["AI/ML", "Analytics", "Enterprise", "Big Data"],
    image: imageMeeting,
    slug: "globaltrade-ai-analytics",
    featured: true,
  },
  {
    id: "PRJ-005",
    title: "Streaming Entertainment Platform",
    client: "StreamFlix Entertainment",
    category: "Web Application",
    status: "completed",
    duration: "24 months",
    year: "2023",
    team: ["Head of Product", "Creative Director", "Video Engineer", "Backend Lead", "ML Engineer", "DevOps Architect"],
    description: "A next-generation video streaming service with 4K HDR, Dolby Atmos, and AI-powered personalization serving 5M+ subscribers.",
    tags: ["Streaming", "Entertainment", "AI", "Media"],
    image: imageLaptop,
    slug: "streamflix-platform",
    featured: true,
  },
  {
    id: "PRJ-006",
    title: "Real Estate CRM System",
    client: "PropertyMax",
    category: "Enterprise Software",
    status: "in-progress",
    duration: "20 weeks",
    year: "2025",
    team: ["Strategy", "Design", "Full-stack", "DevOps"],
    description: "Custom CRM for real estate agents with lead management, property listings, client communication, and automated follow-ups.",
    results: ["Pilot with 100 agents", "30% faster closings", "2x lead conversion"],
    tags: ["Next.js", "Prisma", "PostgreSQL", "Docker"],
    image: imageWhiteboard,
    slug: "real-estate-crm-system",
  },
  {
    id: "PRJ-007",
    title: "Restaurant Ordering App",
    client: "Foodie Express",
    category: "Mobile App",
    status: "completed",
    duration: "8 weeks",
    year: "2023",
    team: ["Product", "UX", "Mobile", "Backend"],
    description: "Native mobile app for food ordering with real-time tracking, multiple payment options, and loyalty rewards program.",
    results: ["50,000+ downloads", "4.7 star rating", "$1M+ revenue"],
    tags: ["React Native", "Node.js", "MongoDB", "Stripe"],
    image: imageLaptop,
    slug: "restaurant-ordering-app",
  },
  {
    id: "PRJ-008",
    title: "Banking Security Portal",
    client: "SecureBank",
    category: "Web Application",
    status: "completed",
    duration: "16 weeks",
    year: "2024",
    team: ["Security", "UX", "Frontend", "Backend"],
    description: "Enterprise-grade security dashboard for fraud detection, transaction monitoring, and risk assessment.",
    results: ["99.9% uptime", "60% faster detection", "PCI DSS compliant"],
    tags: ["Angular", "Java", "Oracle", "Azure"],
    image: imageWhiteboard,
    slug: "banking-security-portal",
  },
  {
    id: "PRJ-009",
    title: "Fitness Tracking Wearable",
    client: "FitPulse",
    category: "Mobile App",
    status: "completed",
    duration: "12 weeks",
    year: "2023",
    team: ["Product", "Design", "Mobile", "IoT"],
    description: "Cross-platform fitness app syncing with wearable devices to track workouts, nutrition, and health metrics.",
    results: ["100,000+ active users", "4.6 star rating", "30% retention increase"],
    tags: ["Flutter", "Firebase", "Bluetooth", "HealthKit"],
    image: imageMeeting,
    slug: "fitness-tracking-wearable",
  },
  {
    id: "PRJ-010",
    title: "NFT Marketplace",
    client: "CryptoArt Hub",
    category: "Web Application",
    status: "completed",
    duration: "10 weeks",
    year: "2022",
    team: ["Strategy", "Design", "Blockchain", "Full-stack"],
    description: "Decentralized marketplace for digital art with wallet integration, minting capabilities, and auction system.",
    results: ["$5M+ in transactions", "2,000+ artists", "50K monthly users"],
    tags: ["Next.js", "Solidity", "IPFS", "Web3.js"],
    image: imageLaptop,
    slug: "nft-marketplace",
  },
  {
    id: "PRJ-011",
    title: "Logistics Management System",
    client: "FastTrack Logistics",
    category: "Enterprise Software",
    status: "completed",
    duration: "18 weeks",
    year: "2024",
    team: ["Strategy", "UX", "Full-stack", "DevOps"],
    description: "End-to-end logistics platform with route optimization, fleet tracking, and automated dispatching.",
    results: ["25% fuel savings", "40% faster delivery", "500+ trucks managed"],
    tags: ["React", "Python", "PostGIS", "AWS"],
    image: imageWhiteboard,
    slug: "logistics-management-system",
  },
  {
    id: "PRJ-012",
    title: "AI Content Generator",
    client: "WriteSmart AI",
    category: "SaaS Platform",
    status: "in-progress",
    duration: "14 weeks",
    year: "2025",
    team: ["AI/ML", "Product", "Design", "Engineering"],
    description: "Generative AI platform for creating marketing copy, blog posts, and social media content with brand voice training. Features include tone adjustment, SEO optimization, and multi-language support.",
    results: ["Beta users: 500+", "95% content quality score", "10x faster writing"],
    tags: ["GPT-4", "Next.js", "Python", "Vector DB"],
    image: imageMeeting,
    slug: "ai-content-generator",
  },
  {
    id: "PRJ-013",
    title: "Smart Home IoT Platform",
    client: "HomeSync Technologies",
    category: "Enterprise Software",
    status: "completed",
    duration: "22 weeks",
    year: "2024",
    team: ["IoT", "Product", "Design", "Embedded", "Cloud"],
    description: "Comprehensive smart home management system connecting lighting, HVAC, security, and appliances. Includes voice control, energy analytics, and predictive maintenance alerts for homeowners and property managers.",
    results: ["10,000+ homes connected", "30% energy savings", "4.8/5 user rating"],
    tags: ["IoT", "AWS IoT", "React", "Node.js", "MQTT"],
    image: imageLaptop,
    slug: "smart-home-iot-platform",
  },
  {
    id: "PRJ-014",
    title: "Video Streaming Service",
    client: "StreamFlix Entertainment",
    category: "Web Application",
    status: "completed",
    duration: "26 weeks",
    year: "2023",
    team: ["Strategy", "UX", "Video", "Backend", "DevOps"],
    description: "Subscription-based video streaming platform with adaptive bitrate streaming, offline downloads, personalized recommendations using ML, and multi-device sync. Supports 4K HDR and Dolby Atmos.",
    results: ["100K subscribers in 3 months", "99.99% uptime", "50M minutes streamed"],
    tags: ["React", "Node.js", "AWS", "CDN", "ML"],
    image: imageWhiteboard,
    slug: "video-streaming-service",
  },
  {
    id: "PRJ-015",
    title: "Supply Chain Analytics",
    client: "GlobalTrade Solutions",
    category: "Enterprise Software",
    status: "completed",
    duration: "18 weeks",
    year: "2024",
    team: ["Data Science", "Product", "Design", "Engineering"],
    description: "AI-powered supply chain optimization platform providing real-time visibility, demand forecasting, route optimization, and risk management. Integrates with ERP systems and shipping carriers worldwide.",
    results: ["20% cost reduction", "50% faster delivery", "$10M+ savings"],
    tags: ["Python", "TensorFlow", "React", "PostgreSQL", "AWS"],
    image: imageMeeting,
    slug: "supply-chain-analytics",
  },
  {
    id: "PRJ-016",
    title: "Telemedicine Platform",
    client: "HealthConnect Global",
    category: "Healthcare",
    status: "completed",
    duration: "20 weeks",
    year: "2023",
    team: ["Healthcare", "UX", "Mobile", "Backend", "Security"],
    description: "Multi-specialty telemedicine platform supporting video consultations, e-prescriptions, lab integrations, and remote patient monitoring. HIPAA and GDPR compliant with end-to-end encryption.",
    results: ["500+ doctors onboarded", "50,000 consultations", "4.9/5 patient rating"],
    tags: ["React Native", "WebRTC", "Node.js", "MongoDB", "AWS"],
    image: imageLaptop,
    slug: "telemedicine-platform",
  },
  {
    id: "PRJ-017",
    title: "Crypto Trading Exchange",
    client: "CoinVault Pro",
    category: "Web Application",
    status: "completed",
    duration: "32 weeks",
    year: "2022",
    team: ["Blockchain", "Security", "Trading", "Backend", "Frontend"],
    description: "Professional-grade cryptocurrency exchange supporting spot trading, futures, margin trading, and staking. Features include real-time order books, advanced charting, API access, and institutional custody solutions.",
    results: ["$100M daily volume", "100,000+ traders", "Zero security breaches"],
    tags: ["React", "Go", "PostgreSQL", "Redis", "AWS"],
    image: imageWhiteboard,
    slug: "crypto-trading-exchange",
  },
  {
    id: "PRJ-018",
    title: "Retail POS System",
    client: "ShopRight Stores",
    category: "Enterprise Software",
    status: "in-progress",
    duration: "16 weeks",
    year: "2025",
    team: ["Retail", "Hardware", "Design", "Engineering", "QA"],
    description: "Next-generation point-of-sale system with inventory management, staff scheduling, customer loyalty programs, and multi-location support. Works offline with cloud sync and supports various payment methods.",
    results: ["200+ stores deployed", "30% faster checkout", "25% inventory accuracy"],
    tags: ["React", "Electron", "SQLite", "Node.js", "Stripe"],
    image: imageMeeting,
    slug: "retail-pos-system",
  },
];

export function getProjectBySlug(slug) {
  return projects.find((p) => p.slug === slug);
}

export function getAllProjectSlugs() {
  return projects.map((p) => p.slug);
}

export const categories = ["All", "Web Application", "E-commerce", "Healthcare", "SaaS Platform", "Education", "Enterprise Software", "Mobile App"];
